title: Yimaj Ahmed | Cybersecurity Professional Portfolio
description: Unraveling the complexities of cybersecurity through reverse engineering, threat analysis, and hands-on security practices.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
